// ignore_for_file: prefer_const_constructors

import 'dart:io';

import 'package:mason/mason.dart';
import 'package:path/path.dart' as path;
import 'package:r13n_hooks/hooks.dart';
import 'package:test/test.dart';

void main() {
  group('$R13nCompatibilityException', () {
    test('toString override is correct', () {
      const message = 'test message';
      expect(
        R13nCompatibilityException(message: message).toString(),
        equals(message),
      );
    });
  });

  group('isCompatibleWithR13n', () {
    test('returns true when the package:r13n version is compatible', () {
      final compatibleVersions = [
        Version.parse('0.1.0-dev.1'),
        Version.parse('0.1.0-dev.2'),
      ];
      for (final version in compatibleVersions) {
        expect(isCompatibleWithR13n(version), isTrue);
      }
    });

    test('returns false when the package:r13n version is incompatible', () {
      final incompatibleVersions = [
        Version.parse('0.1.0-dev'),
        Version.parse('0.1.0'),
        Version.parse('0.1.0'),
        Version.parse('0.2.0'),
        Version.parse('0.3.0'),
        Version.parse('2.0.0'),
      ];
      for (final version in incompatibleVersions) {
        expect(isCompatibleWithR13n(version), isFalse);
      }
    });
  });

  group('ensureRuntimeCompatibility', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync();
    });

    tearDown(() {
      try {
        tempDir.deleteSync(recursive: true);
      } catch (_) {}
    });

    test('throws when a pubspec.lock does not exist', () {
      final expected = 'Expected to find a pubspec.lock in ${tempDir.path}.';
      expect(
        () => ensureRuntimeCompatibility(tempDir),
        throwsA(
          isA<R13nCompatibilityException>().having(
            (e) => e.message,
            'message',
            expected,
          ),
        ),
      );
    });

    test(
        'throws when the pubspec.lock does '
        'not contain a package:r13n dependency', () {
      const expected = '''
Expected to find a dependency on "r13n" in the pubspec.lock

Ensure the "r13n" package is added to your pubspec.yaml and run "flutter pub get" before running "mason make r13n".
''';
      File(path.join(tempDir.path, 'pubspec.lock')).writeAsStringSync(
        '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  not_r13n:
    dependency: "direct main"
    source: hosted
    version: "0.1.0"
sdks:
  dart: ">=2.18.0 <3.0.0"
''',
      );
      expect(
        () => ensureRuntimeCompatibility(tempDir),
        throwsA(
          isA<R13nCompatibilityException>().having(
            (e) => e.message,
            'message',
            expected,
          ),
        ),
      );
    });

    test('throws when the version of package:r13n is incompatible', () {
      const incompatibleVersion = '99.99.99';
      const expected = '''
The current version of "brick:r13n" requires "package:r13n" $compatibleR13nVersion.
Because the current version of "package:r13n" is $incompatibleVersion, version solving failed.''';
      File(path.join(tempDir.path, 'pubspec.lock')).writeAsStringSync(
        '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  r13n:
    dependency: "direct main"
    source: hosted
    version: "$incompatibleVersion"
''',
      );
      expect(
        () => ensureRuntimeCompatibility(tempDir),
        throwsA(
          isA<R13nCompatibilityException>().having(
            (e) => e.message,
            'message',
            expected,
          ),
        ),
      );
    });

    test('completes when the version is compatible.', () {
      File(path.join(tempDir.path, 'pubspec.lock')).writeAsStringSync(
        '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  r13n:
    dependency: "direct main"
    source: hosted
    version: "0.1.0-dev.2"
''',
      );
      expect(() => ensureRuntimeCompatibility(tempDir), returnsNormally);
    });
  });
}
