name: r13n_e2e
description: End to End tests for package:r13n and brick:r13n
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  mason: ^0.1.0-dev.47
  path: ^1.8.3
  test: ^1.19.2
  very_good_analysis: ^4.0.0
