name: mason_publish

on:
  push:
    tags:
      - "r13n_brick-v*.*.*"
  workflow_dispatch:

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1
    with:
      working_directory: "bricks/r13n"
    secrets:
      mason_credentials: ${{ secrets.MASON_CREDENTIALS }}
