name: 🧱🪝 R13n Brick Hooks 
publish_to: 'none'

on: pull_request

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      dart_sdk: "stable"
      working_directory: "bricks/r13n/hooks/"
      analyze_directories: "post_gen.dart pre_gen.dart test"
      report_on: "post_gen.dart pre_gen.dart"