name: r13n_brick

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      dart_sdk: "stable"
      working_directory: "bricks/r13n/hooks/"
      analyze_directories: "post_gen.dart pre_gen.dart test"
      report_on: "post_gen.dart pre_gen.dart"
